sudo: false
language: node_js
cache:
    directories:
        - node_modules
notifications:
    email: false
script:
    - npm run precommit
before_deploy:
    - npm i now --no-save
    - npm run clean-deploys
deploy:
    provider: script
    script: npm run deploy
    skip_cleanup: true
    on:
        branch: master
after_deploy:
    - npm run scale
matrix:
    include:
        - os: linux
          env:
              - APP_NAME='meetupjs' BOTS_PATH='../bots.json' CALENDAR_API_URL='http://calendar-api.now.sh/' CHANNEL='#general' INSTANCE_NAME='meetupjs-slack-bot' NODE_ENV='test'
